version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 80:8000
    depends_on:
      - postgres
    networks:
      - bound
  
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    networks:
      - bound
    
volumes:
  postgres_data:

networks:
  bound:
    driver: bridge
