"""empty message

Revision ID: 278c0ec3354e
Revises: afbeed694326
Create Date: 2024-08-22 22:31:10.775431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278c0ec3354e'
down_revision: Union[str, None] = 'afbeed694326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_end',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_end', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_end')
    )
    op.execute("INSERT INTO file_end (file_end) VALUES ('mp3')")
    op.execute("INSERT INTO file_end (file_end) VALUES ('wav')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_end')
    # ### end Alembic commands ###
