"""empty message

Revision ID: 7a94e94fc78b
Revises: 278c0ec3354e
Create Date: 2024-08-23 10:57:24.207107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a94e94fc78b'
down_revision: Union[str, None] = '278c0ec3354e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musics', sa.Column('hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'musics', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'musics', type_='unique')
    op.drop_column('musics', 'hash')
    # ### end Alembic commands ###
